### ISSUE TITLE
Petstore ambassador example results in a 404 error. 

### ISSUE THREAD

**Issue by AloisReitbauer** [kubeshop/kusk#193]
**Describe the bug**
I ran the petstore ambassador example and it results in a 404 which means the service is not exposed. 

**To Reproduce**
just follow the doc instructions

**Expected behavior**

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
```
curl -kLi 'https://localhost:8443/petstore/api/v3/pet/findByStatus?status=available'

HTTP/2 404 
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
content-length: 19
date: Sun, 14 Nov 2021 06:49:26 GMT
```

**Comment by kylehodgetts** [comment]
Hello @AloisReitbauer I will be looking at this today

**Comment by kylehodgetts** [comment]
@AloisReitbauer Could you tell me which version of Kubernetes you were using?

**Comment by AloisReitbauer** [comment]
I am running 1.19

**Comment by kylehodgetts** [comment]
Okay, I will also test this on 1.19
