### ISSUE TITLE
[Bug]: kusk uses private Kubernetes annotations

### ISSUE THREAD

**Issue by sftim** [kubeshop/kusk#49]
### What happened?

https://kubeshop.github.io/kusk-gateway/guides/autodeploy/ shows a recommendation that readers use annotations with keys like `kusk-gateway/openapi-url`

For [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) and [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/), keys that don't contain a `.` are private and “belong to” the cluster's operator. A project like Kusk should use a public annotation key such as `gateway.kusk.example/openapi-url`, so that it is not infringing on the cluster operator's area of responsibility.

### Version

1.0.0 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jasmingacic** [comment]
@sftim I wanted to follow up on this issue. 

The service annotations were an experimental feature and we are thinking about removing it from kusk-gateway. Were you trying to use it for some specific use case?

**Comment by sftim** [comment]
If they're experimental, removing the annotation fixes the issue just fine. If they are kept, they should have a namespace set.

**Comment by jasmingacic** [comment]
We are going to remove it in the next release.

**Comment by jasmingacic** [comment]
@sftim if you are interested in a demo we'd be glad to organize it for you.

**Comment by sftim** [comment]
What was the code change that fixed this? I can't see which one that is.
